name       : android-tools
version    : 5.1
release    : 1
source     :
    - https://github.com/ubports/android-tools/archive/5.1-r1.tar.gz : e90593579c1b4b3806b23e509a10465e0548fcf968a018d13e989972c8c9fd96
license    : Apache-2.0
summary    : Android development tools (adb and fastboot)
component  : programming.tools
description: |
    Android development tools, this includes adb (android debug bridge) and fastboot (diagnostic protocol for androids fastboot bootloader)
builddeps  :
    - pkgconfig(libselinux)
setup      : |
    #Patch for obsolete use of major() and minor() to fix build
    %patch -p2 < $pkgfiles/major_minor.patch
build      : |
    %make
install    : |
    %make_install
