name       : android-tools
version    : 33.0.3
release    : 20
source     :
    - git|https://github.com/nmeum/android-tools : 33.0.3p1
    - git|https://github.com/M0Rf30/android-udev-rules : 20220903
license    :
    - Apache-2.0
    - GPL-3.0-or-later
homepage   : https://developer.android.com/studio/releases/platform-tools
summary    : Android development tools (adb and fastboot)
component  : programming.tools
description: |
    Android development tools, this includes adb (android debug bridge) and fastboot (diagnostic protocol for androids fastboot bootloader)
clang      : yes
networking : yes
builddeps  :
    - pkgconfig(libbrotlicommon)
    - pkgconfig(liblz4)
    - pkgconfig(libselinux)
    - pkgconfig(libsepol)
    - pkgconfig(libpcre2-8)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libzstd)
    - pkgconfig(protobuf)
    - golang
    - gtest-devel
setup      : |
    rm -rf vendor/selinux
    %patch -p1 < $pkgfiles/use_local_selinux_lib.patch

    git config --global user.email "copyright@getsol.us"
    git config --global user.name "Solus"
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00755 $sources/android-udev-rules.git/51-android.rules $installdir/usr/lib/udev/rules.d/51-android.rules

    # we don't need licence file and this one is installed in odd location, so just remove it
    rm -rf $installdir/usr/share/licenses
