name       : android-tools
version    : 29.0.6
release    : 6
source     :
    - git|https://android.googlesource.com/platform/system/core : platform-tools-29.0.6
    - git|https://android.googlesource.com/platform/system/extras : platform-tools-29.0.6
    - git|https://android.googlesource.com/platform/system/tools/mkbootimg : platform-tools-29.0.6
    - git|https://android.googlesource.com/platform/external/f2fs-tools : platform-tools-29.0.6
    - git|https://android.googlesource.com/platform/external/e2fsprogs : platform-tools-29.0.6
    - git|https://android.googlesource.com/platform/external/avb : platform-tools-29.0.6
    - git|https://android.googlesource.com/platform/frameworks/native : platform-tools-29.0.6
    # https://android.googlesource.com/platform/external/boringssl/+/platform-tools-29.0.6/BORINGSSL_REVISION
    - git|https://boringssl.googlesource.com/boringssl : a7a75f208caea8a303615724d4cc5f4e8dfb9695
    # originaly downloaded from https://android.googlesource.com/platform/frameworks/base/+archive/platform-tools-29.0.6/libs/androidfw.tar.gz
    - https://getsol.us/sources/androidfw-29.0.6.tar.gz : d4bd55b614f47e820ef9d59844218604b30eae143da21a8b7898081c57f7e459
    - git|https://github.com/M0Rf30/android-udev-rules : 20191103
extract    : no
license    :
    - Apache-2.0
    - GPL-3.0-or-later
homepage   : https://developer.android.com/studio/releases/platform-tools
summary    : Android development tools (adb and fastboot)
component  : programming.tools
description: |
    Android development tools, this includes adb (android debug bridge) and fastboot (diagnostic protocol for androids fastboot bootloader)
clang      : yes
builddeps  :
    - pkgconfig(libselinux)
    - pkgconfig(libsepol)
    - pkgconfig(libpcre2-8)
    - pkgconfig(libusb-1.0)
    - golang
    - gtest-devel
    - protobuf-devel
    - ruby
    - vim
environment: |
    export PLATFORM_TOOLS_VERSION=%version%
setup      : |
    # Make src dir and enter it
    mkdir -p src && cd src

    # Copy sources
    for src in $sources/*.git ; do
        git_dir=${src#$sources/}
        cp -r "$src" "${git_dir%.git}"
    done

    mkdir -p base/libs/androidfw
    tar -xzvf $sources/androidfw-%version%.tar.gz -C base/libs/androidfw

    # deployagent.jar should be built from sources, but to do that, we need whole Android SDK
    # to avoid making this build too complicated, we include prebuilt binary and copy it into sources
    cp $pkgfiles/deployagent.jar core/adb

    # Patch the sources so they can build on Solus
    %patch -p1 < $pkgfiles/fix_build_core.patch -d core
    sed -i 's|/usr/bin/env python$|/usr/bin/env python2|g' avb/avbtool
    sed -i 's|/usr/bin/env python$|/usr/bin/env python2|g' mkbootimg/mkbootimg.py
    sed -i 's|/usr/bin/env python$|/usr/bin/env python2|g' mkbootimg/unpack_bootimg.py

    # Generate ninja build files
    $pkgfiles/generate_build.rb > build.ninja
    mkdir -p boringssl/build && cd boringssl/build && cmake -GNinja ..
build      : |
    ninja %JOBS% -C boringssl/build
    ninja %JOBS%
install    : |
    install -Dm00755 -t $installdir/usr/bin adb fastboot mke2fs.android e2fsdroid ext2simg avb/avbtool
    install -Dm00755 mkbootimg/mkbootimg.py $installdir/usr/bin/mkbootimg
    install -Dm00755 mkbootimg/unpack_bootimg.py $installdir/usr/bin/unpack_bootimg
    install -Dm00755 android-udev-rules/51-android.rules $installdir/usr/lib/udev/rules.d/51-android.rules
