name       : android-tools
version    : 30.0.5
release    : 8
source     :
    - git|https://android.googlesource.com/platform/system/core : platform-tools-30.0.5
    - git|https://android.googlesource.com/platform/system/extras : platform-tools-30.0.5
    - git|https://android.googlesource.com/platform/system/libbase : platform-tools-30.0.5
    - git|https://android.googlesource.com/platform/system/libziparchive : platform-tools-30.0.5
    - git|https://android.googlesource.com/platform/system/tools/mkbootimg : platform-tools-30.0.5
    - git|https://android.googlesource.com/platform/external/f2fs-tools : platform-tools-30.0.5
    - git|https://android.googlesource.com/platform/external/e2fsprogs : platform-tools-30.0.5
    - git|https://android.googlesource.com/platform/external/avb : platform-tools-30.0.5
    - git|https://android.googlesource.com/platform/frameworks/native : platform-tools-30.0.5
    - git|https://android.googlesource.com/platform/external/boringssl : platform-tools-30.0.5
    # originaly downloaded from https://android.googlesource.com/platform/frameworks/base/+archive/platform-tools-30.0.5/libs/androidfw.tar.gz
    - https://getsol.us/sources/androidfw-30.0.5.tar.gz : bde8ee93dd16b55a55ffef7b837bb3d71f338094f4d55b607208ace23d243428
    - git|https://github.com/M0Rf30/android-udev-rules : 20201003
extract    : no
license    :
    - Apache-2.0
    - GPL-3.0-or-later
homepage   : https://developer.android.com/studio/releases/platform-tools
summary    : Android development tools (adb and fastboot)
component  : programming.tools
description: |
    Android development tools, this includes adb (android debug bridge) and fastboot (diagnostic protocol for androids fastboot bootloader)
clang      : yes
builddeps  :
    - pkgconfig(libbrotlicommon)
    - pkgconfig(liblz4)
    - pkgconfig(libselinux)
    - pkgconfig(libsepol)
    - pkgconfig(libpcre2-8)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libzstd)
    - pkgconfig(protobuf)
    - golang
    - gtest-devel
    - ruby
    - vim
environment: |
    export PLATFORM_TOOLS_VERSION=%version%
setup      : |
    # Make src dir and enter it
    mkdir -p src && cd src

    # Copy sources
    for src in $sources/*.git ; do
        git_dir=${src#$sources/}
        cp -r "$src" "${git_dir%.git}"
    done

    mkdir -p base/libs/androidfw
    tar -xzvf $sources/androidfw-%version%.tar.gz -C base/libs/androidfw

    # deployagent.jar should be built from sources, but to do that, we need whole Android SDK
    # to avoid making this build too complicated, we include prebuilt binary and copy it into sources
    # to extract prebuilt deployagent.jar, download prebuilt adb binary, execute `./adb install --fastdeploy someapp.apk`
    # and fetch it with `adb pull /data/local/tmp/deployagent.jar` from your phone
    cp $pkgfiles/deployagent.jar core/adb

    # Patch the sources so they can build on Solus
    %patch -p1 < $pkgfiles/fix_build_core.patch -d core
    %patch -p1 < $pkgfiles/fix_libziparchive.patch -d libziparchive
    %patch -p1 < $pkgfiles/boringssl-disable-thirdpartydeps.patch -d boringssl
    sed -i 's|/usr/bin/env python$|/usr/bin/env python2|g' avb/avbtool
    sed -i 's|/usr/bin/env python$|/usr/bin/env python2|g' mkbootimg/mkbootimg.py
    sed -i 's|/usr/bin/env python$|/usr/bin/env python2|g' mkbootimg/unpack_bootimg.py

    # Generate ninja build files
    # Originaly taken from https://github.com/anatol/android-platform-tools-build
    # With permission to redistribute from original author Anatol Pomozov <anatol.pomozov@gmail.com>
    # Slightly modified to suit Solus' build system
    $pkgfiles/generate_build.rb > build.ninja
    mkdir -p boringssl/src/build && cd boringssl/src/build && cmake -GNinja ..
build      : |
    ninja %JOBS% -C boringssl/src/build crypto/libcrypto.a ssl/libssl.a
    ninja %JOBS%
install    : |
    install -Dm00755 -t $installdir/usr/bin adb fastboot mke2fs.android e2fsdroid ext2simg avb/avbtool
    install -Dm00755 mkbootimg/mkbootimg.py $installdir/usr/bin/mkbootimg
    install -Dm00755 mkbootimg/unpack_bootimg.py $installdir/usr/bin/unpack_bootimg
    install -Dm00755 android-udev-rules/51-android.rules $installdir/usr/lib/udev/rules.d/51-android.rules
